apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: demo
spec:
  ports:
    - name: http-mysql
      port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: mysql
  type: NodePort
