apiVersion: v1
kind: Service             #表示Kubernetes Service
metadata:
  name: mysql-v2-svc      #Service的名称
  namespace: demo         #命名空间
spec:
  ports:
    - name: http-mysql
      port: 3306               #Service提供服务的端口号
      targetPort: 3306      #容器内的端口号
      nodePort: 30002      #暴露出外网的端口号
  selector:
    app: mysql-v2         #Service对应的Pod的标签
  type: NodePort
