apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: demo
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - containerPort: 3306  
    env:
    - name: MYSQL_ROOT_PASSWORD   
      value: "123456"
