apiVersion: v1
kind: Secret
metadata:
  name: harbor-member-site
  namespace: demo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovLzY5LjIzNC4yMzUuNzA6MzAwMDIiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiVmFsb3IxMjMiLCJlbWFpbCI6ImFkbWluIiwiYXV0aCI6IllXUnRhVzQ2Vm1Gc2IzSXhNak09In19fQ==
